apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lab
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
allowVolumeExpansion: true
parameters:
  numberOfReplicas: '1'
  staleReplicaTimeout: '30'
  migratable: 'true'
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
