apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-lab
  annotations:
    {}
    #  key: string
  labels:
    {}
    #  key: string
allowVolumeExpansion: true
parameters:
  numberOfReplicas: '1'
  staleReplicaTimeout: '30'
  migratable: 'true'
  #  key: string
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
#allowedTopologies:
#  - matchLabelExpressions:
#      - key: string
#        values:
#          - string
#mountOptions:
#  - string