apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  annotations:
    harvesterhci.io/storageClassName: longhorn-lab
  name: sle-15-sp5-20240719
  labels:
    harvesterhci.io/image-type: raw_qcow2
    harvesterhci.io/imageDisplayName: "opensuse-leap-15.6"
    harvesterhci.io/os-type: openSUSE
  namespace: default
spec:
  checksum: ""
  displayName: opensuse
  pvcName: ""
  pvcNamespace: ""
  retry: 3
  sourceType: download
  url: http://10.0.9.10/images/sle-knode-20240719-sm.qcow2
