apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  annotations:
    harvesterhci.io/storageClassName: longhorn-lab
  name: sle15-sp6-gold
  labels:
    harvesterhci.io/image-type: raw_qcow2
    harvesterhci.io/imageDisplayName: "sle15-sp6-gold-20250216"
    harvesterhci.io/os-type: openSUSE
  namespace: default
spec:
  checksum: ""
  displayName: opensuse
  pvcName: ""
  pvcNamespace: ""
  retry: 3
  sourceType: download
  url: http://10.0.9.10/images/sle15-sp6-20250215.qcow2
